GuitarWeb/GuitarWeb/Models/Amplifier.cs
using System;

namespace GuitarWeb.Models
{
    [Serializable]
    public class Amplifier
    {
        public string RegNumber { get; set; }
        public string Manefacturer { get; set; }
        public string Model { get; set; }
        public int ProductionYear { get; set; }
    }
}

GuitarWeb/GuitarWeb/Models/Guitar.cs
using System;

namespace GuitarWeb.Models
{
    [Serializable]
    public class Guitar
    {
        public string RegNumber { get; set; }
        public string Model { get; set; }
        public int ProductionYear { get; set; }
    }
}

GuitarWeb/GuitarWeb/Controllers/AmplifierController.cs
using System.Web.Mvc;

namespace GuitarWeb.Controllers
{
    public class AmplifierController : Controller
    {
        //
        // GET: /Amplifier/

        public ActionResult AmplifierList()
        {
            ViewBag.Message = "My Amps";
            return View();
        }

    }
}

GuitarWeb/GuitarWeb/Controllers/GuitarController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using GuitarWeb.Interfaces;
using GuitarWeb.Models;
using GuitarWeb.Repository;
using System.Linq;


namespace GuitarWeb.Controllers
{
    public class GuitarController : Controller
    {
        private readonly IGuitarRepository _guitarRepository = new GuitarRepository();

        public ActionResult GuitarList()
        {
            ViewBag.Message = "All your guitars";

            return View(_guitarRepository.GetGuitars());
        }

        public ActionResult Edit(string id)
        {
            ViewBag.Message = "All your guitars";

            return View(_guitarRepository.GetGuitarById(id));
        }

        [HttpPost]
        public JsonResult GetGuitar(string id)
        {
            return Json(_guitarRepository.GetGuitarById(id));
        }

        [HttpPost]
        public JsonResult GetGuitars()
        {
            return Json(_guitarRepository.GetGuitars());
        }
        

        [HttpPost] 
        public ViewResult Edit(Guitar guitar) { 

            if (!TryUpdateModel(guitar)) { 
                ViewBag.updateError = "Update Failure"; 
                return View(guitar); 
            }

            var guitars = _guitarRepository.GetGuitars();

            UpdateGuitarsWithChanges(guitars, guitar);

            _guitarRepository.SaveGuitars(guitars);
 
            return View("GuitarList", _guitarRepository.GetGuitars()); 
        }

        [HttpPost]
        public ActionResult Delete(string guitarId)
        {
            var guitars = _guitarRepository.GetGuitars();

            var guitarToDelete = (from g in guitars where g.RegNumber == guitarId select g).FirstOrDefault();

            if (guitarToDelete != null)
            {
                guitars.Remove(guitarToDelete);

                _guitarRepository.SaveGuitars(guitars);
            }

            return Json(guitars);
        }

        public ActionResult New()
        {
            ViewBag.Message = "New guitar";

            return View(new Guitar());
        }

        [HttpPost]
        public ViewResult New(Guitar guitar)
        {
            var guitars = _guitarRepository.GetGuitars();

            guitars.Add(guitar);

            _guitarRepository.SaveGuitars(guitars);

            return View("GuitarList", guitars);
        }

       

        private void UpdateGuitarsWithChanges(IEnumerable<Guitar> guitars, Guitar guitar)
        {
            var editedGuitar = guitars.Where(g => g.RegNumber == guitar.RegNumber).FirstOrDefault();

            if (editedGuitar != null)
            {
                editedGuitar.ProductionYear = guitar.ProductionYear;
                editedGuitar.Model = guitar.Model;
            }
                
        }
    }
}

GuitarWeb/GuitarWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuitarWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your quintessential app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your quintessential contact page.";

            return View();
        }
    }
}

GuitarWeb/GuitarWeb/Views/Amplifier/AmplifierList.cshtml
@model IEnumerable<GuitarWeb.Models.Amplifier>

@{
    ViewBag.Title = "AmplifierList";
}

<h2>AmplifierList</h2>

GuitarWeb/GuitarWeb/Views/Amplifier/Edit.cshtml
@model GuitarWeb.Models.Amplifier

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

GuitarWeb/GuitarWeb/Views/Guitar/Delete.cshtml
@model GuitarWeb.Models.Guitar

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>

<h3>Are you sure you want to delete this?</h3>
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
<fieldset>
    <legend>Guitar</legend>

    <div class="editor-label">
         @Html.EditorFor(model => model.RegNumber)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RegNumber)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Model)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Model)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ProductionYear)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProductionYear)
    </div>
    <p> <input type="submit" value="Delete" /> </p>
</fieldset>

    <p>
       
        @Html.ActionLink("Back to List", "GuitarList")
    </p>
}

GuitarWeb/GuitarWeb/Views/Guitar/Edit.cshtml
@model GuitarWeb.Models.Guitar

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Guitar</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.RegNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RegNumber)
            @Html.ValidationMessageFor(model => model.RegNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Model)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Model)
            @Html.ValidationMessageFor(model => model.Model)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProductionYear)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ProductionYear)
            @Html.ValidationMessageFor(model => model.ProductionYear)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "GuitarList")
</div>

GuitarWeb/GuitarWeb/Views/Guitar/GuitarList.cshtml
@model IEnumerable<GuitarWeb.Models.Guitar>

@{
    ViewBag.Title = "GuitarList";
}


<script src="~/Scripts/GuitarScripts.js"></script>

<h2>GuitarList</h2>

<p>
    @Html.ActionLink("Create New", "New")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RegNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductionYear)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RegNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Model)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductionYear)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.RegNumber}) 
            <button title="Delete" value="Show details" id="ButtonA" onclick="javascript:DeleteGuitar(@item.RegNumber);" />
             <button title="List" id="Buttonb" onclick="javascript:GetGuitars();" />
          
        </td>
    </tr>
}
    
</table>

GuitarWeb/GuitarWeb/Views/Guitar/New.cshtml
@model GuitarWeb.Models.Guitar

@{
    ViewBag.Title = "New";
}

<h2>New</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Guitar</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.RegNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RegNumber)
            @Html.ValidationMessageFor(model => model.RegNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Model)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Model)
            @Html.ValidationMessageFor(model => model.Model)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProductionYear)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ProductionYear)
            @Html.ValidationMessageFor(model => model.ProductionYear)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "GuitarList")
</div>

GuitarWeb/GuitarWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin luctus tincidunt justo nec tempor. 
        Aliquam erat volutpat. Fusce facilisis ullamcorper consequat. Vestibulum non sapien lectus. Nam 
        mi augue, posuere at tempus vel, dignissim vitae nulla. Nullam at quam eu sapien mattis ultrices. 
        Quisque quis leo mi, at lobortis dolor. Nullam scelerisque facilisis placerat. Fusce a augue 
        erat, malesuada euismod dui. Duis iaculis risus id felis volutpat elementum. Fusce blandit iaculis 
        quam a cursus. Cras varius tincidunt cursus. Morbi justo eros, adipiscing ac placerat sed, posuere 
        et mi. Suspendisse vulputate viverra aliquet. Duis non enim a nibh consequat mollis ac tempor 
        lorem. Phasellus elit leo, semper eu luctus et, suscipit at lacus. In hac habitasse platea 
        dictumst. Duis dignissim justo sit amet nulla pulvinar sodales.
    </p>

    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin luctus tincidunt justo nec tempor. 
        Aliquam erat volutpat. Fusce facilisis ullamcorper consequat. Vestibulum non sapien lectus. Nam 
        mi augue, posuere at tempus vel, dignissim vitae nulla. Nullam at quam eu sapien mattis ultrices. 
        Quisque quis leo mi, at lobortis dolor. Nullam scelerisque facilisis placerat. Fusce a augue 
        erat, malesuada euismod dui. Duis iaculis risus id felis volutpat elementum. Fusce blandit iaculis 
        quam a cursus. Cras varius tincidunt cursus. Morbi justo eros, adipiscing ac placerat sed, posuere 
        et mi. Suspendisse vulputate viverra aliquet. Duis non enim a nibh consequat mollis ac tempor 
        lorem. Phasellus elit leo, semper eu luctus et, suscipit at lacus. In hac habitasse platea 
        dictumst. Duis dignissim justo sit amet nulla pulvinar sodales.
    </p>

    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin luctus tincidunt justo nec tempor. 
        Aliquam erat volutpat. Fusce facilisis ullamcorper consequat. Vestibulum non sapien lectus. Nam 
        mi augue, posuere at tempus vel, dignissim vitae nulla. Nullam at quam eu sapien mattis ultrices. 
        Quisque quis leo mi, at lobortis dolor. Nullam scelerisque facilisis placerat. Fusce a augue 
        erat, malesuada euismod dui. Duis iaculis risus id felis volutpat elementum. Fusce blandit iaculis 
        quam a cursus. Cras varius tincidunt cursus. Morbi justo eros, adipiscing ac placerat sed, posuere 
        et mi. Suspendisse vulputate viverra aliquet. Duis non enim a nibh consequat mollis ac tempor 
        lorem. Phasellus elit leo, semper eu luctus et, suscipit at lacus. In hac habitasse platea 
        dictumst. Duis dignissim justo sit amet nulla pulvinar sodales.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Fusce facilisis ullamcorper consequat. Vestibulum non sapien lectus. Nam 
        mi augue, posuere at tempus vel, dignissim vitae nulla.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

GuitarWeb/GuitarWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone:</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email:</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address:</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

GuitarWeb/GuitarWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@section featured {
<section class="featured">
    <div class="content-wrapper">
        <hgroup class="title">
            <h1>@ViewBag.Title.</h1>
            <h2>@ViewBag.Message</h2>
        </hgroup>
        <p>
            To learn more about ASP.NET MVC visit <a href="http://asp.net/mvc" title="ASP.NET MVC Website">http://asp.net/mvc</a>. 
            The page features <span class="highlight">videos, tutorials, and samples</span> to help you get the most from 
            ASP.NET MVC. If you have any questions about ASP.NET MVC visit 
            <a href="http://forums.asp.net/1146.aspx/1?MVC" title="ASP.NET MVC Forum">our forums</a>.
        </p>
    </div>
</section>
}

<h3>We suggest the following:</h3>

<ol class="round">
    <li class="one">
        <h5>Configure ASP.NET Membership</h5>
        ASP.NET membership gives you a built-in way to create, store, and 
        validate user credentials (authentication). By default, membership works with a local instance of SQL Server, 
        but you can configure it to use another database.
    </li>
    <li class="two">
        <h5>Add NuGet packages and jump start your coding</h5>
        NuGet makes it easy to install and update free libraries and tools in Visual Studio. In <em>Solution Explorer</em>, 
        right-click the <em>References</em> node, select <em>Manage NuGet Packages</em>, and then pick from the extensive 
        list of packages.
    </li>
    <li class="three">
        <h5>Setup deployment to your web server</h5>
        Use Microsoft Web Deploy to quickly and easily publish your application to a web server. 
        In <em>Solution Explorer</em>, right-click your project, select <em>Publish</em>, 
        and choose one of the many options to get your code deployed and running on the web.
    </li>
</ol>

<section class="features">
    <section class="feature">
        <img src="~/Images/aspNetHome.png" alt="" />
        <h3>Home of ASP.NET</h3>
        <p>
            ASP.NET is a free, fully supported Web application framework that helps you create standards-based web solutions. 
            Whether you're new to ASP.NET or an experienced developer, the <a href="http://asp.net">ASP.NET website</a> 
            is your source for news, training, downloads, and support.
        </p>
    </section>
    <section class="feature">
        <img src="~/Images/NuGetGallery.png" alt="" />
        <h3>NuGet Gallery</h3>
        <p>
            NuGet is a Visual Studio extension that makes it easy to install and update open source libraries and tools in 
            Visual Studio. To see available packages, visit the <a href="http://nuget.org">NuGet gallery</a>.
            You can also develop your own package and share it in the gallery.
        </p>
    </section>
    <section class="feature">
        <img src="~/Images/findHosting.png" alt="" />
        <h3>Find Web Hosting</h3>
        <p>
            You can easily find a web hosting company that offers the right mix of features and price for your applications. 
            Visit <a href="http://microsoft.com/web/hosting" title="Microsoft/Web Website">Microsoft.com/web</a> to 
            explore offerings from many providers.
        </p>
    </section>
</section>

GuitarWeb/GuitarWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <link href="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/css")" rel="stylesheet" type="text/css" />
        <link href="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/themes/base/css")" rel="stylesheet" type="text/css" />
        <script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Scripts/js")"></script>
        <meta name="viewport" content="width=device-width" />
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here.", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        Hello, <span class="username">@User.Identity.Name</span>!
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Guitars", "GuitarList", "Guitar")</li>
                            <li>@Html.ActionLink("Amps", "AmplifierList", "Amplifier")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
                <div class="float-right">
                    <ul id="social">
                        <li><a href="http://facebook.com" class="facebook">Facebook</a></li>
                        <li><a href="http://twitter.com" class="twitter">Twitter</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </body>
</html>